import type { User, Task } from "../types";

export const mockUsers: User[] = [
  { id: 1, name: "劉承恩", email: "admin@test.com", role: "admin" },
  { id: 2, name: "林宜蓁", email: "li.xiaohua@company.com", role: "member" },
  {
    id: 3,
    name: "謝佳穗",
    email: "zhang.xiaofang@company.com",
    role: "member",
  },
  { id: 4, name: "黃柏翰", email: "chen.dawen@company.com", role: "member" },
  { id: 5, name: "林志偉", email: "lin.zhiwei@company.com", role: "member" },
  { id: 6, name: "黃雅婷", email: "huang.yating@company.com", role: "member" },
  { id: 7, name: "吳建志", email: "wu.jianzhi@company.com", role: "member" },
  { id: 8, name: "劉怡君", email: "liu.yijun@company.com", role: "admin" },
  { id: 9, name: "蔡宗翰", email: "tsai.zonghan@company.com", role: "member" },
  { id: 10, name: "許雅雯", email: "hsu.yawen@company.com", role: "member" },
  { id: 11, name: "楊志豪", email: "yang.zhihao@company.com", role: "member" },
  {
    id: 12,
    name: "鄭佳穎",
    email: "cheng.jiaying@company.com",
    role: "member",
  },
];

export const mockTasks: Task[] = [
  {
    id: 1,
    title: "設計登入頁面",
    description: "完成登入頁面的 UI 設計與 RWD 實作",
    status: "done",
    assignee: "林宜蓁",
    createdAt: "2024-01-01",
    dueDate: "2024-01-10",
  },
  {
    id: 2,
    title: "實作任務管理 API",
    description: "串接後端任務管理相關 RESTful API",
    status: "in-progress",
    assignee: "謝佳穗",
    createdAt: "2024-01-05",
    dueDate: "2024-01-20",
  },
  {
    id: 3,
    title: "撰寫單元測試",
    description: "針對核心功能撰寫單元測試，覆蓋率需達 80%",
    status: "todo",
    assignee: "黃柏翰",
    createdAt: "2024-01-08",
    dueDate: "2024-01-25",
  },
  {
    id: 4,
    title: "優化頁面載入效能",
    description: "分析並優化各頁面載入速度，目標 LCP 在 2.5 秒內",
    status: "todo",
    assignee: "劉承恩",
    createdAt: "2024-01-10",
    dueDate: "2024-01-30",
  },
  {
    id: 5,
    title: "使用者權限管理",
    description: "實作角色與權限控管機制，區分 admin 與 member",
    status: "in-progress",
    assignee: "王林耘",
    createdAt: "2024-01-12",
    dueDate: "2024-02-01",
  },
  {
    id: 6,
    title: "串接第三方金流",
    description: "整合綠界金流 API，支援信用卡與超商付款",
    status: "todo",
    assignee: "黃雅婷",
    createdAt: "2024-01-15",
    dueDate: "2024-02-10",
  },
  {
    id: 7,
    title: "建立 CI/CD 流程",
    description: "設定 GitHub Actions 自動化測試與部署流程",
    status: "done",
    assignee: "吳建志",
    createdAt: "2024-01-18",
    dueDate: "2024-02-05",
  },
  {
    id: 8,
    title: "重構元件架構",
    description: "將共用邏輯抽離為 composables，提升可維護性",
    status: "in-progress",
    assignee: "劉怡君",
    createdAt: "2024-01-20",
    dueDate: "2024-02-15",
  },
  {
    id: 9,
    title: "多語系支援",
    description: "整合 vue-i18n，支援繁中、簡中、英文切換",
    status: "todo",
    assignee: "蔡宗翰",
    createdAt: "2024-01-22",
    dueDate: "2024-02-20",
  },
  {
    id: 10,
    title: "撰寫 API 文件",
    description: "使用 Swagger 撰寫完整的 API 文件",
    status: "done",
    assignee: "許雅雯",
    createdAt: "2024-01-25",
    dueDate: "2024-02-08",
  },
];
